proxy:
  title: OP Survey Analysis
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 80
  authentication: simple
  forward-headers-strategy: framework
  admin-groups: scientists
  users:
    - name: admin
      password: admin123
      groups: scientists
    - name: user
      password: user123
      groups: mathematicians
  
  # Docker configuration
  docker:
    internal-networking: true
    port-range-start: 20000
    network: internal_op_shiny
  
  # Application definition
  specs:
  - id: op-survey
    display-name: OP Survey Analysis
    description: Survey data analysis application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server', port=3838)"]
    container-image: op_shiny
    container-network: internal_op_shiny
