services:
  op_shiny:
    build: 
      context: .
    container_name: op_shiny
    restart: unless-stopped
    volumes:
      # Bind mount for survey data (host path to container path)
      - ./survey_data:/srv/shinyapp/survey_data
    networks:
      - default
  
  nginx_op_shiny:
    image: nginx:alpine
    container_name: nginx_op_shiny
    restart: unless-stopped
    depends_on: 
      - op_shiny
    volumes:
     - ./.htpasswd:/etc/nginx/.htpasswd:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment: 
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
     - default
     - outside

networks:
  default:
    external:
      name: internal_op_shiny
  outside:
    external:
      name: connect-to-proxy
