FROM nginx:alpine

RUN apk add --no-cache logrotate dcron

COPY logrotate.conf /etc/logrotate.d/nginx

RUN echo "30 3 * * * /usr/sbin/logrotate -f /etc/logrotate.d/nginx" | crontab -

RUN echo '#!/bin/sh' > /entrypoint.sh && \
    echo 'crond -l 2 -f &' >> /entrypoint.sh && \
    echo 'exec nginx -g "daemon off;"' >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
