services:
  shinyproxy:
    image: openanalytics/shinyproxy:latest
    container_name: shinyproxy
    restart: unless-stopped
    group_add:
      - ${DOCKER_GID:-998}
    expose:
      - "8080"
    environment:
      - PROXY_URL=https://${VIRTUAL_HOST}
    volumes:
      - ./application.yml:/opt/shinyproxy/application.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

  shiny-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: shiny-nginx:latest
    container_name: shiny-nginx
    depends_on:
      - shinyproxy
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs-nginx:/var/log/nginx
    networks:
      - default
      - outside

networks:
  default:
    external:
      name: internal_op_shiny
  outside:
    external:
      name: connect-to-proxy
