services:
  shinyproxy:
    image: openanalytics/shinyproxy:latest
    container_name: shinyproxy
    restart: unless-stopped
    group_add:
      - ${DOCKER_GID:-998}
    expose:
      - "80"
    volumes:
      - ./application.yml:/opt/shinyproxy/application.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - outside

networks:
  default:
    external:
      name: internal_op_shiny
  outside:
    external:
      name: connect-to-proxy
