APP_TITLE <- "CPSC Experience Survey Explorer"
APP_VERSION <- "1.0.0"
APP_DESCRIPTION <- "Survey analysis tool for course instructors"

DATA_FILE_PATH <- "survey_data/CPSC Experience Survey.csv"
DATA_ENCODING <- "UTF-8"

PLOT_WIDTH <- 800
PLOT_HEIGHT <- 400
PLOT_ASPECT_RATIO <- PLOT_WIDTH / PLOT_HEIGHT

TABLE_PAGE_SIZE <- 30
TABLE_SHOW_ALL_ROWS <- FALSE
TABLE_SCROLLX <- TRUE
TABLE_SCROLLY <- TRUE

ANIMATION_DURATION <- 300
ANIMATION_DELAY <- 100

LIKERT_MIN_VALUE <- 1
LIKERT_MAX_VALUE <- 5
LIKERT_LABELS <- c(
  "1 - Strongly Disagree",
  "2",
  "3",
  "4",
  "5 - Strongly Agree"
)


SECTION_DISPLAY_FORMAT <- "{course} - {time}"
SECTION_SORT_ORDER <- c("231 - 1pm", "231 - 11am", "231 - 3pm", "217 - 1pm", "217 - 11am", "217 - 3pm")

DEFAULT_SECTION_FILTER <- NULL
DEFAULT_CATEGORY_FILTER <- "course_satisfaction"

STATISTICS_DISPLAY_N <- TRUE
STATISTICS_DISPLAY_MEAN <- TRUE
STATISTICS_DISPLAY_MEDIAN <- TRUE
STATISTICS_DISPLAY_MODE <- TRUE
STATISTICS_DISPLAY_SD <- TRUE
STATISTICS_DISPLAY_SE <- TRUE
STATISTICS_DISPLAY_MIN <- TRUE
STATISTICS_DISPLAY_MAX <- TRUE
STATISTICS_DISPLAY_Q1 <- TRUE
STATISTICS_DISPLAY_Q3 <- TRUE
STATISTICS_DISPLAY_MISSING <- TRUE

PLOT_THEME <- ggplot2::theme_bw() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.title = ggplot2::element_text(size = 12),
    axis.text = ggplot2::element_text(size = 10),
    legend.position = "bottom",
    panel.grid.minor = ggplot2::element_blank()
  )

PLOT_GIRAFE_OPTIONS <- list(
  width = 100,
  height = 100
)

ERROR_TOAST_DURATION <- 5
ERROR_TOAST_TYPE <- "error"
WARNING_TOAST_DURATION <- 3
WARNING_TOAST_TYPE <- "warning"

LOG_LEVEL <- "WARNING"
LOG_TO_CONSOLE <- TRUE
LOG_TO_FILE <- FALSE
LOG_FILE_PATH <- "logs/app.log"

DATA_CACHE_ENABLED <- TRUE
PLOT_CACHE_ENABLED <- TRUE
LAZY_LOAD_INSIGHTS <- TRUE

ENABLE_SCREEN_READER <- TRUE
ENABLE_FOCUS_INDICATORS <- TRUE
ENABLE_HIGH_CONTRAST_MODE <- FALSE

EXPORT_FORMAT <- "csv"
EXPORT_ENCODING <- "UTF-8"
EXPORT_SEPARATOR <- ","
EXPORT_QUOTE <- "\""
EXPORT_DECIMAL <- "."
EXPORT_THOUSANDS <- ","
